# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mtech
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-myapp
  namespace: mtech
  labels:
    app: app-myapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: app-myapp
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-myapp
  namespace: mtech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-myapp
  template:
    metadata:
      labels:
        app: app-myapp
    spec:
      containers:
        - name: container-myapp
          image: myapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080